kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://localhost:5000"]
nodes:
  - role: control-plane
    # port forward 80 on the host to 80 on this node
    extraPortMappings:
      # agent port
      - containerPort: 18126
        hostPort: 18126
        # optional: set the bind address on the host
        # 0.0.0.0 is the current default
        listenAddress: "127.0.0.1"
        # optional: set the protocol to one of TCP, UDP, SCTP.
        # TCP is the default
        protocol: TCP
      # app port
      - containerPort: 18080
        hostPort: 18080
        # optional: set the bind address on the host
        # 0.0.0.0 is the current default
        listenAddress: "127.0.0.1"
        # optional: set the protocol to one of TCP, UDP, SCTP.
        # TCP is the default
        protocol: TCP
