apiVersion: v1
kind: Pod
metadata:
  name: sample-app
  namespace: default
spec:
  initContainers:
    - name: node-init
      image: bengl/test-auto-inst:latest  # put the library image here
      imagePullPolicy: Never
      command: ["sh", "copy-dd-trace.sh", "/autoinstrumentation"]
      volumeMounts:
        - name: autoinstrumentation
          mountPath: /autoinstrumentation
  containers:
    - name: app
      image: bengl/test-sample-app # put the app image here
      env:
        - name: NODE_OPTIONS
          value: --require=/autoinstrumentation/node_modules/dd-trace/init
        - name: DD_TRACE_DEBUG
          value: "true"
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: autoinstrumentation
          mountPath: /autoinstrumentation
    - name: test-agent
      image: ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent:latest
      env:

  volumes:
    - name: autoinstrumentation
      emptyDir: {}
