issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/dd-trace-js:pull_request

claim_pattern:
  actor: dependabot\[bot\]
  event_name: pull_request
  ref: refs/pull/[0-9]+/merge
  job_workflow_ref: DataDog/dd-trace-js/\.github/workflows/dependabot-automation.yml@refs/pull/[0-9]+/merge

permissions:
  contents: write
  pull_requests: write
