name: Update 3rd-party licenses

on:
  pull_request_target:
    branches:
      - master
    paths:
      - 'yarn.lock'

jobs:
  update-3rdparty-licenses:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    env:
      REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
    steps:
      - name: Check out PR branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get GitHub token with appropriate permissions
        uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
        id: octo-sts
        with:
          scope: DataDog
          policy: dd-trace-js-license-attribution-read

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.14'

      - name: Check out dd-license-attribution
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: watson/dd-license-attribution
          ref: f529f30734809b971799002cb6e4fa1bb039a359
          path: dd-license-attribution

      - name: Install dd-license-attribution
        working-directory: dd-license-attribution
        run: |
          pip install .

      - name: Create mirrors.json for PR branch
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          HEAD_REF: ${{ github.head_ref }}
        run: |
          cat > mirrors.json <<EOF
          [
            {
              "original_url": "${REPOSITORY_URL}",
              "mirror_url": "${REPOSITORY_URL}",
              "ref_mapping": {
                "branch:${DEFAULT_BRANCH}": "branch:${HEAD_REF}"
              }
            }
          ]
          EOF

      - name: Regenerate LICENSE-3rdparty.csv
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          dd-license-attribution generate-sbom-csv \
            --use-mirrors=mirrors.json \
            --no-scancode-strategy \
            --no-github-sbom-strategy \
            --yarn-subdir vendor \
            "${REPOSITORY_URL}" > LICENSE-3rdparty.csv

      - name: Append vendored dependencies
        run: |
          cat .github/vendored-dependencies.csv >> LICENSE-3rdparty.csv

      - name: Run LICENSE-3rdparty.csv update check
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_USER_TYPE: ${{ github.event.pull_request.user.type }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: ./.github/scripts/update-3rdparty-licenses.sh
